### ISSUE TITLE
TypeError: doc.pushToAlgolia is not a function

### ISSUE THREAD

**Issue by DulanDev** [algolia/mongoolia#1]
I get this error. here is my model.

const mongoose = require('mongoose');
const Schema = mongoose.Schema;
var algoliasearch = require('algoliasearch');
const mongoolia = require('mongoolia').default;

//create jobs schema and model
const CompanySchema = new Schema({
     name: {
         type: String,
         required: [true, 'Company Name field is required.']
     },
     about: {
        type: String,
        required: [true, 'Description field is required.']
    },
    profilePic: {
        type: String,
        required: [true, 'Image link is required.']
    },
    registeredDate: {
        type: Date,
        default: Date.now
    },
    jobsPosted: {
        type: Array,
        required: [true, 'Array of Job ids is required.']
    },
    telephone: {
        type: String,
        required: [true, 'Telephone field is required.']
    },
    email: {
        type: String,
        required: [true, 'Email Address is required.']
    },
    website: {
        type: String,
        required: [false]
    },
}); 

// Specify your Algolia credentials which you can find into your dashboard
CompanySchema.plugin(mongoolia, {
    appId: 'xx',
    apiKey: 'xxx',
    indexName: 'company'
});

const Company = mongoose.model('company',CompanySchema);

Company.syncWithAlgolia().then(function(data){
    console.log(data);
}).catch(function(err){
    console.log(err);
});

module.exports = Company;

**Comment by iam4x** [comment]
Hi @Dulan666 

What version of mongoose are you using and what version of node?
Is it possible that you push a repro case so I can debug it?

**Comment by johnernaut** [comment]
I'm having this same issue with a basic model set up as shown above.

Mongoolia version: `"mongoolia": "^1.0.3"`
Node version: `9.9.0`
Mongoose version: `"mongoose": "^4.13.7"`

**Comment by Haroenv** [comment]
@johnernaut, could it be possible to make a repo with a reproduction case?

**Comment by johnernaut** [comment]
@Haroenv Absolutely!  I've made a repo with this issue reproducible here:  [https://github.com/johnernaut/apollo-engine-error](https://github.com/johnernaut/apollo-engine-error)  (ignore the name - the repo was previously used to demonstrate an issue in another project).

Here's the output of running that project:
![screen shot 2018-04-02 at 8 09 44 am](https://user-images.githubusercontent.com/504361/38197394-7822b024-364d-11e8-88ec-367100c79dae.png)

**Comment by johnernaut** [comment]
I'm a doofus.  I was attempting `ModelSchema.syncWithAlgolia` instead of `Model.syncWithAlgolia`.  This functionality is working as intended.

**Comment by mfissehaye** [comment]
I am using `Model.syncWithAlgolia()` but the exact same error is happening to me.
node version v10.16.3
mongoose@4.13.19
mongoolia@1.0.3

```
(node:6428) UnhandledPromiseRejectionWarning: TypeError: doc.pushToAlgolia is not a function
    at C:\Users\123\Documents\code\node\appname\node_modules\mongoolia\dist\algolia-mongoose-model.js:44:22
    at Array.map (<anonymous>)
    at C:\Users\123\Documents\code\node\appname\node_modules\mongoolia\dist\algolia-mongoose-model.js:43:32
    at Generator.next (<anonymous>)
    at step (C:\Users\123\Documents\code\node\appname\node_modules\mongoolia\dist\algolia-mongoose-model.js:13:191)
    at C:\Users\123\Documents\code\node\appname\node_modules\mongoolia\dist\algolia-mongoose-model.js:13:361
    at tryCatcher (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (C:\Users\123\Documents\code\node\appname\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by shardaishwak** [comment]
So was there a solution to this error or not?
