### ISSUE TITLE
TypeError: doc.pushToAlgolia is not a function

### ISSUE THREAD

**Issue by palkerecsenyi** [algolia/mongoolia#4]
I'm trying to use Mongoolia with my project and I've encountered an error that I can't explain.

```js
// the userSchema is defined here, excluded for brevity
userSchema.plugin(mongoolia, {
    appId: "<redacted>",
    apiKey: "<redacted>",
    indexName: "<redacted>"
});

const User = mongoose.model("User", userSchema);

User.syncWithAlgolia()
    .catch(err => { console.log(err); });
```

As far as I know, this seems right. I've also set the `algoliaIndex: true` values where appropriate and imported Mongoolia with:
```js
const mongoolia = require("mongoolia").default;
```

However, I get this error:

```
TypeError: doc.pushToAlgolia is not a function
    at C:\Users\Administrator.GRAPH-PC\Documents\PROJECTS\CDR-App\node_modules\mongoolia\dist\algolia-mongoose-model.js:44:22
    at Array.map (<anonymous>)
    at C:\Users\Administrator.GRAPH-PC\Documents\PROJECTS\CDR-App\node_modules\mongoolia\dist\algolia-mongoose-model.js:43:32
    at Generator.next (<anonymous>)
    at step (C:\Users\Administrator.GRAPH-PC\Documents\PROJECTS\CDR-App\node_modules\mongoolia\dist\algolia-mongoose-model.js:13:191)
    at C:\Users\Administrator.GRAPH-PC\Documents\PROJECTS\CDR-App\node_modules\mongoolia\dist\algolia-mongoose-model.js:13:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Any ideas?
Thank you, and please feel free to ask for any more code that you may need to reproduce my issue.

**Comment by Haroenv** [comment]
Did you try making the model before initialising the plugin?

**Comment by Haroenv** [comment]
A GitHub project I can clone would be ideal for debugging :)

**Comment by palkerecsenyi** [comment]
I'll try your suggestion later today, and I'll make a repo if it doesn't work. Thanks for your reply.

**Comment by palkerecsenyi** [comment]
I've tried it, and it works perfectly. Thanks for your help!

**Comment by Haroenv** [comment]
Great to hear
